// Re-export all data types for use in components.
// Import from here, not from @/data/mockData directly.
export type {
  NavLink,
  NavData,
  SocialPlatform,
  SocialLink,
  FooterData,
  HeroData,
  ToolsGridItem,
  ToolsGridData,
  ServiceTool,
  ServiceSpec,
  ServiceDetail,
  ServicesPageData,
  ProjectCategory,
  ProjectDetail,
  TechnicalStandard,
  ProjectsPageData,
  ProjectType,
  ContactInfoItem,
  AgentData,
  GearPartnerData,
  ContactPageData,
  GalleryImage,
  GalleryPageData,
  SiteData,
} from '@/data/mockData';
