// Re-export all data types for use in components.
// Import from here, not from @/data/mockData directly.
export type {
  NavLink,
  NavData,
  SocialPlatform,
  SocialLink,
  FooterData,
  HeroData,
  SpecItem,
  SpecsStripData,
  ServicesTeaserItem,
  ServicesTeaserData,
  FeaturedProject,
  FeaturedProjectsData,
  ServiceTool,
  ServiceSpec,
  ServiceDetail,
  ServicesPageData,
  ProjectCategory,
  ProjectDetail,
  FilterTab,
  TechnicalStandard,
  ProjectsPageData,
  ProjectType,
  ContactInfoItem,
  ContactPageData,
  SiteData,
} from '@/data/mockData';
